services:
  server:
    build:
      context: ./server
    container_name: resumecraft-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_GRAPHQL_URL: http://localhost:4000/graphql
        NEXT_PUBLIC_STACK_PROJECT_ID: ${NEXT_PUBLIC_STACK_PROJECT_ID:-demo}
        NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: ${NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY}
        STACK_SECRET_SERVER_KEY: ${STACK_SECRET_SERVER_KEY}
    container_name: resumecraft-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - server
    restart: unless-stopped


