name: Deploy Server (Render Hook + GHCR)

on:
  push:
    branches: [ deploy-v1 ]
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build & Push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/resumecraft-server:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/resumecraft-server:latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trigger_render:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "❌ RENDER_DEPLOY_HOOK secret not set"
            exit 1
          fi
          
          echo "🚀 Triggering Render deployment..."
          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST "$RENDER_DEPLOY_HOOK")
          
          http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d: -f2)
          body=$(echo "$response" | sed '/HTTP_STATUS:/d')
          
          echo "Response body: $body"
          echo "HTTP status: $http_status"
          
          if [ "$http_status" = "200" ] || [ "$http_status" = "201" ]; then
            echo "✅ Deployment triggered successfully"
          else
            echo "❌ Deployment trigger failed with status: $http_status"
            exit 1
          fi