name: Deploy Server (Render Hook + GHCR)

on:
  push:
    branches: [ deploy-v1 ]
    paths:
      - 'server/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/resumecraft-server:${{ github.sha }}

  trigger_render:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"


